---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRESQL_VERSION}
  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: openebs-hostpath

  superuserSecret:
    name: cloudnative-pg-cluster-secret

  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
      hugepages-2Mi: 2Gi # Requires sysctl set on the host

  monitoring:
    enablePodMonitor: true

  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore: &barmanObjectStore
  #     data:
  #       compression: bzip2
  #     wal:
  #       compression: bzip2
  #       maxParallel: 8

  #     destinationPath: s3://backups/pg-default/
  #     endpointURL: https://nas.hive.internal:9000

  #     # Note: serverName version needs to be inclemented
  #     # when recovering from an existing cnpg cluster
  #     serverName: postgres-v22
  #     s3Credentials:
  #       accessKeyId:
  #         name: cloudnative-pg-secret
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: cloudnative-pg-secret
  #         key: AWS_SECRET_ACCESS_KEY

  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres-v21
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster
