---
# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/refs/heads/main/pkg/config/v1alpha5/schema.json
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab-config
image: rancher/k3s:latest
servers: 1
agents: 2
options:
  # k3s:
  #   extraArgs:
  #     - arg: --disable=traefik
  #       nodeFilters:
  #         - server:*
  #     - arg: --disable=coredns
  #       nodeFilters:
  #         - server:*
  #     - arg: --disable=servicelb
  #       nodeFilters:
  #         - server:*
  #     - arg: --flannel-backend=none
  #       nodeFilters:
  #         - server:*
  #     - arg: --disable-network-policy
  #       nodeFilters:
  #         - server:*
  #     - arg: --disable-kube-proxy
  #       nodeFilters:
  #         - server:*
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
