---
# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/refs/heads/main/pkg/config/v1alpha5/schema.json
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab-config
servers: 1
agents: 2
options:
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
