---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/kubernetes/bootstrap"
  TALOS_DIR: "{{.ROOT_DIR}}/talos"

  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync

tasks:
  default:
    cmd: task --list-all
    silent: true
