---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  INFRASTRUCTURE_DIR: "{{.ROOT_DIR}}/infrastructure"

  K3D_CONFIG: "{{.ROOT_DIR}}/cluster.yaml"
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  dev: .taskfiles/dev
  infra: .taskfiles/infra
  bootstrap: .taskfiles/bootstrap

tasks:
  default:
    cmd: task --list-all
    silent: true
