---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tvarr
spec:
  chartRef:
    kind: OCIRepository
    name: tvarr
  interval: 1h
  values:
    controllers:
      tvarr:
        containers:
          app:
            image:
              repository: ghcr.io/jmylchreest/tvarr
              tag: 0.0.26@sha256:3daf9046c1f7d6a9d69c5f75e0a0ab2a646ddc84856378f96a2c1e7e92262596
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Europe/Rome
              TVARR_SERVER_PORT: &port 8080
              TVARR_SERVER_BASE_URL: https://tvarr.marcocondrache.com
              TVARR_DATABASE_DSN: /data/tvarr.db
              TVARR_STORAGE_BASE_DIR: /data
              TVARR_LOGGING_LEVEL: info
              TVARR_GRPC_ENABLED: "false"
              TVARR_FFMPEG_BINARY_PATH: /usr/bin/ffmpeg
              TVARR_FFMPEG_PROBE_PATH: /usr/bin/ffprobe
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /livez
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /livez
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.marcocondrache.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
