---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: registry-secret

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      website:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/marcocondrache/marcocondrache.com # {"$imagepolicy": "laboratory:website:name"}
              tag: 1.0.3@sha256:3bdfb7718fa980785debb6cde8bc7bf7afffec3ca3b5453bcb722ac0ecdc00b0 # {"$imagepolicy": "laboratory:website:tag"}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    service:
      app:
        controller: website
        ports:
          http:
            port: &port 4321

    route:
      app:
        hostnames:
          - marcocondrache.com
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: default
        rules:
          - backendRefs:
              - name: website
                port: *port
