---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagepolicy_v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: website
spec:
  imageRepositoryRef:
    name: website
  policy:
    semver:
      range: ">=1.0.0"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: website
spec:
  image: ghcr.io/marcocondrache/marcocondrache.com
  secretRef:
    name: registry-secret
  interval: 5m
