---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-postgres
    creationPolicy: Owner
    template:
      data:
        DB_NAME: immich
        DB_USERNAME: immich
        DB_PASSWORD: "{{ .IMMICH_PASSWORD }}"
  dataFrom:
    - extract:
        key: postgres
