---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich
spec:
  postgresVersion: 17

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        parameters:
          search_path: '"$user", public, vector"'
        pg_hba:
          - hostnossl all all 10.42.0.0/16 md5
          - hostssl all all all md5

  instances:
    - name: database
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-local

  users:
    - name: immich
      options: "SUPERUSER"
      databases:
        - immich

  # backups:
  #   pgbackrest:
  #     repos:
  #       - name: repo1
  #         volume:
  #           volumeClaimSpec:
  #             accessModes:
  #               - "ReadWriteOnce"
  #             resources:
  #               requests:
  #                 storage: 10Gi
