---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich
spec:
  postgresVersion: 17

  instances:
    - name: immich
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-local

  users:
    - name: immich
      databases:
        - immich
      password:
        ref:
          name: immich-database
          key: DB_PASSWORD

  databaseInitSQL:
    key: init-database
    name: immich-database-init
