---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich
spec:
  # TODO: find better image
  postgresVersion: 16
  image: ghcr.io/budimanjojo/cdpgvecto.rs:16@sha256:2a54142d7a2becd027025e95ac3e4542f7688621f3a63fe131a8fec6a65ccc49
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        parameters:
          shared_preload_libraries: "vectors.so"
          search_path: '"$user", public, vectors"'
        pg_hba:
          - hostnossl all all 10.42.0.0/16 md5
          - hostssl all all all md5

  instances:
    - name: database
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-local

  users:
    - name: immich
      options: "SUPERUSER"
      databases:
        - immich

  # backups:
  #   pgbackrest:
  #     repos:
  #       - name: repo1
  #         volume:
  #           volumeClaimSpec:
  #             accessModes:
  #               - "ReadWriteOnce"
  #             resources:
  #               requests:
  #                 storage: 10Gi
