---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich
spec:
  postgresVersion: 17

  instances:
    - name: database
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-local

  backups:
    pgbackrest:
      repos:
        - name: database
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 10Gi

  databaseInitSQL:
    key: init.sql
    name: immich-database-init
