---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webcheck
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      webcheck:
        containers:
          webcheck:
            image:
              repository: ghcr.io/lissy93/web-check
              tag: latest

    service:
      app:
        controller: webcheck
        ports:
          http:
            port: 3000

    route:
      webcheck:
        hostnames:
          - webcheck.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: webcheck
                port: 3000
