---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  VOLSYNC_TASK_RESOURCES_DIR: "{{.ROOT_DIR}}/.taskfiles/volsync/resources"

tasks:
  unlock:
    desc: Unlock all restic source repos
    preconditions:
      - which kubectl
    vars:
      SOURCES:
        sh: kubectl get replicationsources --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    cmds:
      - for:
          var: SOURCES
          split: "\n"
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} patch --field-manager=flux-client-side-apply replicationsources {{splitList "," .ITEM | last}} --type merge --patch "{\"spec\":{\"restic\":{\"unlock\":\"{{now | unixEpoch}}\"}}}"

  snapshot:
    desc: Snapshot an app [NS=default] [APP=required]
    preconditions:
      - which kubectl
      - kubectl --namespace {{.NS}} get replicationsources {{.APP}}
    requires:
      vars:
        - APP
    vars:
      WAIT: '{{.WAIT | default "true"}}'
      NS: '{{.NS | default "default"}}'
      JOB: volsync-src-{{.APP}}
    cmds:
      - kubectl --namespace {{.NS}} patch replicationsources {{.APP}} --type merge -p '{"spec":{"trigger":{"manual":"{{now | unixEpoch}}"}}}'
      - |-
        {{ if eq "true" .WAIT }}until kubectl --namespace {{.NS}} get job/{{.JOB}} &>/dev/null; do sleep 5; done{{ end }}
      - |-
        {{ if eq "true" .WAIT }}kubectl --namespace {{.NS}} wait job/{{.JOB}} --for=condition=complete --timeout=120m{{ end }}
