---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: m3u-editor
spec:
  chartRef:
    kind: OCIRepository
    name: m3u-editor
  interval: 1h
  values:
    controllers:
      m3u-editor:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/sparkison/m3u-editor
              tag: 0.11.43@sha256:77a08ed5dea1d525e9befea5b70db8a7f5e59d5f3c686475d97898879df36a78
            env:
              APP_PORT: &port 36400
              APP_URL: http://m3u.marcocondrache.com
              DB_CONNECTION: sqlite
              DISABLE_SYNC_LOGS: true
              ENABLE_POSTGRES: false
              M3U_PROXY_ENABLED: false
              M3U_PROXY_HOST: 10.43.221.85
              M3U_PROXY_PORT: 38085
              NGINX_ENABLED: true
              REDIS_ENABLED: false
              REDIS_HOST: m3u-editor-dragonfly.default.svc.cluster.local
              REDIS_SERVER_PORT: 6379
              SESSION_DRIVER: database
              TZ: Europe/Rome
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /up
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /up
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "kube-system",
            "ips": ["10.0.100.10/24"],
            "mac": "3e:d0:83:c0:8e:13"
          }]
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - m3u.marcocondrache.com
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/config
            subPath: config
          - path: /var/www/html/storage/app/public
            subPath: storage-public
      tmp:
        type: emptyDir
