---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.1/install/kubernetes/cilium/values.schema.json
ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

k8sServiceHost: "127.0.0.1"
k8sServicePort: "6444"

routingMode: native
ipv4NativeRoutingCIDR: "10.0.0.0/8"
installNoConntrackIptablesRules: true

rollOutCiliumPods: true

endpointRoutes:
  enabled: true

loadBalancer:
  acceleration: native

bpf:
  masquerade: true

gatewayAPI:
  enabled: true
  enableAlpn: true

encryption:
  enabled: true
  type: wireguard

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true

MTU: 1450
