---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.1/install/kubernetes/cilium/values.schema.json
cluster:
  id: 0
  name: lab-config

kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443

routingMode: "native"
ipv4NativeRoutingCIDR: 10.42.0.0/16

operator:
  replicas: 1
  rollOutPods: true

l2announcements:
  enabled: false

externalIPs:
  enabled: true

bpf:
  masquerade: true

ipam:
  mode: kubernetes

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
