---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.1/install/kubernetes/cilium/values.schema.json
cluster:
  id: 0
  name: lab-config

kubeProxyReplacement: true
k8sServiceHost: "127.0.0.1"
k8sServicePort: "6444"

debug:
  enabled: true

routingMode: "native"
ipv4NativeRoutingCIDR: "10.0.1.0/24"

endpointRoutes:
  enabled: true

rollOutCiliumPods: true

devices: "enp7s0"

cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

gatewayAPI:
  enabled: true
  enableAlpn: true

envoy:
  enabled: true
  rollOutPods: true

bpf:
  masquerade: true

operator:
  replicas: 1
  rollOutPods: true

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

encryption:
  enabled: true
  type: wireguard

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
