---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.1/install/kubernetes/cilium/values.schema.json
cluster:
  id: 0
  name: lab-config

kubeProxyReplacement: true
k8sServiceHost: "127.0.0.1"
k8sServicePort: "6444"

# TODO: investigate why native routing is not working (probably nix issues)
routingMode: "tunnel"
tunnelProtocol: "vxlan"

rollOutCiliumPods: true

cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
  externalTrafficPolicy: Local

endpointRoutes:
  enabled: true

envoy:
  enabled: true
  rollOutPods: true

localRedirectPolicy: true

operator:
  replicas: 1
  rollOutPods: true

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

encryption:
  enabled: true
  type: wireguard

ipam:
  mode: kubernetes

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
