---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16
installNoConntrackIptablesRules: true

autoDirectNodeRoutes: true

cni:
  exclusive: false

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l2announcements:
  enabled: false

endpointRoutes:
  enabled: true

loadBalancer:
  mode: dsr
  algorithm: maglev

gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1

rollOutCiliumPods: true

bandwidthManager:
  enabled: true
  bbr: true

envoy:
  enabled: true
  rollOutEnvoyPods: true
  prometheus:
    serviceMonitor:
      enabled: true

localRedirectPolicy: true

operator:
  replicas: 1
  rollOutPods: true
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

bpfClockProbe: true

bgpControlPlane:
  enabled: true

bpf:
  masquerade: true
  datapathMode: netkit
  preallocateMaps: true

encryption:
  enabled: true
  type: wireguard

enableIPv4BIGTCP: true
enableIPv6BIGTCP: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

hubble:
  enabled: false

devices: bond+

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
