---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.1/install/kubernetes/cilium/values.schema.json
cluster:
  id: 0
  name: lab-config

kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6444

autoDirectNodeRoutes: true

routingMode: "native"
ipv4NativeRoutingCIDR: 10.42.0.0/16

rollOutCiliumPods: true

cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

gatewayAPI:
  enabled: true
  enableAlpn: true

bandwidthManager:
  enabled: true
  bbr: true

loadBalancer:
  algorithm: maglev

envoy:
  enabled: true
  rollOutPods: true

localRedirectPolicy: true

operator:
  replicas: 1
  rollOutPods: true

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

l2announcements:
  enabled: false

bpf:
  masquerade: true

ipam:
  mode: kubernetes

hubble:
  enabled: false
