---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hive-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hive-runner-secret
    template:
      data:
        github_app_id: "{{ .APP_ID }}"
        github_app_installation_id: "{{ .INSTALLATION_ID }}"
        github_app_private_key: "{{ .SSHKEY }}"
  dataFrom:
    - extract:
        key: github-app
