---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-client
spec:
  commonName: home-assistant-client
  duration: 43800h
  issuerRef:
    kind: Issuer
    name: home-assistant-client-ca
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Never
    size: 256
  renewBefore: 720h
  secretName: home-assistant-client
  usages:
    - client auth
    - digital signature
