---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: home-assistant-client-ca
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: home-assistant-client-ca
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &crt tls.crt
        remoteRef:
          remoteKey: home-assistant-client-ca
          property: *crt
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: home-assistant-client-ca
          property: *key
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: home-assistant-client
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: home-assistant-client
  template:
    data:
      ca.crt: '{{ index . "ca.crt" | b64enc }}'
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &ca ca.crt
        remoteRef:
          remoteKey: home-assistant-client
          property: *ca
    - match:
        secretKey: &crt tls.crt
        remoteRef:
          remoteKey: home-assistant-client
          property: *crt
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: home-assistant-client
          property: *key
