---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.18.1
  url: oci://ghcr.io/home-operations/charts-mirror/cilium
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ipam:
      mode: kubernetes

    k8s:
      requireIPv4PodCIDR: true
      requireIPv6PodCIDR: true

    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445

    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6NativeRoutingCIDR: fdf3:0f3a:242e:42::/108

    routingMode: native

    autoDirectNodeRoutes: true

    cni:
      exclusive: false

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    l2announcements:
      enabled: false

    endpointRoutes:
      enabled: true

    loadBalancer:
      mode: dsr
      algorithm: maglev

    gatewayAPI:
      enabled: true
      enableAlpn: true
      xffNumTrustedHops: 1

    rollOutCiliumPods: true

    bandwidthManager:
      enabled: true
      bbr: true

    envoy:
      enabled: true
      rollOutEnvoyPods: true
      prometheus:
        serviceMonitor:
          enabled: true

    localRedirectPolicy: true

    operator:
      replicas: 1
      rollOutPods: true
      dashboards:
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true

    bpfClockProbe: true

    bgpControlPlane:
      enabled: true

    bpf:
      masquerade: true
      datapathMode: netkit
      preallocateMaps: true

    encryption:
      enabled: true
      type: wireguard

    ipv4:
      enabled: true
    ipv6:
      enabled: true

    enableIPv4BIGTCP: true
    enableIPv6BIGTCP: true

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    devices: bond+

    hubble:
      enabled: false

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
