cluster:
  etcd:
    advertisedSubnets:
      - 10.0.30.0/24
  allowSchedulingOnControlPlanes: true
  coreDNS:
    disabled: true
  proxy:
    disabled: true
  apiServer:
    extraArgs:
      runtime-config: admissionregistration.k8s.io/v1alpha1=true
      feature-gates: MutatingAdmissionPolicy=true
  scheduler:
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - schedulerName: default-scheduler
          pluginConfig:
            - name: PodTopologySpread
              args:
                defaultingType: List
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
