---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: towonel-agent-secret
    creationPolicy: Owner
    template:
      data:
        TOWONEL_INVITE_TOKEN: "{{ .TOWONEL_INVITE_TOKEN }}"
  dataFrom:
    - extract:
        key: towonel
