---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 2h
  url: https://netdata.github.io/helmchart/
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 30m
  releaseName: netdata
  chart:
    spec:
      chart: netdata
      version: 3.7.129
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: monitoring

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    image:
      repository: netdata/netdata
      tag: "v2.3.1"

    parent:
      enabled: true

    child:
      enabled: false

    k8sState:
      enabled: false
