---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      nocodb:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

        containers:
          app:
            image:
              repository: docker.io/nocodb/nocodb
              tag: 0.264.6@sha256:e104655c6ba71398faeaeb85cc118a0194e362c6d6f9a619f5bd7a99d3621b2b
            env:
              PORT: &port 8080
              NC_JWT_EXPIRES_IN: 48h
              NC_REDIS_URL: redis://nocodb-redis.default.svc.cluster.local:6379
              NC_PUBLIC_URL: "https://{{ .Release.Name }}.marcocondrache.com"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.3
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 3000

    service:
      app:
        controller: nocodb
        ports:
          http:
            port: *port

      redis:
        controller: redis
        ports:
          http:
            port: 6379

    route:
      app:
        hostnames:
          - nocodb.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          nocodb:
            app:
              - path: /usr/app/data

      redis:
        existingClaim: "{{ .Release.Name }}-redis-data"
        advancedMounts:
          redis:
            app:
              - path: /data
