---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-cifs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-cifs
    template:
      data:
        CIFS_USERNAME: "{{ .CIFS_USERNAME }}"
        CIFS_PASSWORD: "{{ .CIFS_PASSWORD }}"
  dataFrom:
    - extract:
        key: storage-box
