---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.8.1
  values:
    persistence:
      defaultClass: false

    defaultSettings:
      defaultDataPath: /var/mnt/data
      defaultReplicaCount: 1
      storageMinimalAvailablePercentage: 10
      storageReservedPercentageForDefaultDisk: 0
      allowCollectingLonghornUsageMetrics: false
