# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: longhorn
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# provisioner: driver.longhorn.io
# allowVolumeExpansion: true
# reclaimPolicy: Delete
# volumeBindingMode: Immediate
# parameters:
#   fsType: "ext4"
#   dataEngine: v1
#   numberOfReplicas: "2"
#   staleReplicaTimeout: "30"
#   dataLocality: "best-effort"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: "ext4"
  dataEngine: v1
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "strict-local"
