---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hcloud-csi
spec:
  interval: 1h
  url: https://charts.hetzner.cloud
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: hcloud-csi
      sourceRef:
        kind: HelmRepository
        name: hcloud-csi
      version: 2.13.0
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: hcloud-csi
    storageClasses:
      - name: hcloud-volumes
        defaultStorageClass: true
        reclaimPolicy: Delete
        # extraParameters:
        #   csi.storage.k8s.io/node-publish-secret-name: hcloud-csi-secret
        #   csi.storage.k8s.io/node-publish-secret-namespace: kube-system
