---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./pdf/ks.yaml
  - ./n8n/ks.yaml
  - ./plex/ks.yaml
  - ./immich/ks.yaml
  - ./fusion/ks.yaml
  - ./it-tools/ks.yaml
  - ./paperless/ks.yaml
  - ./home-assistant/ks.yaml
