---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./fusion/ks.yaml
  - ./it-tools/ks.yaml
  - ./ocis/ks.yaml
  - ./paperless/ks.yaml
  - ./home-assistant/ks.yaml
  - ./zigbee/ks.yaml
  # TODO: Increase UMA for gpu
  # https://github.com/ollama/ollama/pull/5426
  # - ./ai/ks.yaml
