---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: silence-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    alertmanagerAddress: http://alertmanager-operated.observability.svc.cluster.local:9093
    image:
      registry: quay.io
      # TODO: Why do we need to specify the tag?
      tag: 0.18.0
    networkPolicy:
      enabled: false
