---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: m3u-proxy
spec:
  chartRef:
    kind: OCIRepository
    name: m3u-proxy
  interval: 1h
  values:
    controllers:
      m3u-proxy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/sparkison/m3u-proxy
              tag: 0.4.14@sha256:232abde531626b63e008ce01f1c55d5e31349223f7ba29553fbf9712c32721e6
            env:
              CLEANUP_INTERVAL: 120
              ENABLE_REDIS_POOLING: true
              HLS_TEMP_DIR: /hls
              HLS_BROADCAST_DIR: /hls/broadcast
              LOG_LEVEL: DEBUG
              PORT: &port 38085
              REDIS_DB: 6
              REDIS_ENABLED: true
              REDIS_HOST: m3u-editor-dragonfly.default.svc.cluster.local
              REDIS_POOL_MAX_CONNECTIONS: 25
              REDIS_PORT: 6379
              STREAM_TIMEOUT: 180
              TZ: Europe/Rome
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "kube-system",
            "ips": ["10.0.100.11/24"],
            "mac": "3e:d0:83:c0:8e:14"
          }]
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      hls:
        type: emptyDir
        medium: Memory
      tmp:
        type: emptyDir
