---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ai
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ai:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          ollama:
            image:
              repository: ollama/ollama
              tag: v0.9.6
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
                amd.com/gpu: 1
              limits:
                memory: 4Gi
                amd.com/gpu: 1

          openwebui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.16
            resources:
              requests:
                cpu: 500m
                memory: 500Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            env:
              - name: OLLAMA_BASE_URL
                value: "https://ai.marcocondrache.com"

    service:
      app:
        controller: ai
        ports:
          ollama:
            port: 11434
          openwebui:
            port: &port 8080

    persistence:
      openwebui:
        existingClaim: ai
        advancedMounts:
          ai:
            openwebui:
              - path: /app/backend/data

      models:
        existingClaim: ollama
        advancedMounts:
          ai:
            ollama:
              - path: /root/.ollama

    route:
      app:
        hostnames:
          - ai.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: openwebui
                port: *port
