---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ai
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ai:
        replicas: 1

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          ollama:
            image:
              repository: ollama/ollama
              tag: 0.11.4-rocm
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
                amd.com/gpu: 1
              limits:
                memory: 8Gi
                amd.com/gpu: 1
            env:
              - name: HSA_OVERRIDE_GFX_VERSION
                value: 11.0.0

          openwebui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.6.22
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 4Gi
            env:
              PORT: 8080
              DATA_DIR: /data
              OLLAMA_BASE_URL: http://ai.default.svc.cluster.local:11434

              WEBUI_URL: https://ai.marcocondrache.com
              WEBUI_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: ai-secret
                    key: WEBUI_SECRET_KEY

    defaultPodOptions:
      securityContext:
        supplementalGroups: [3000]

    service:
      app:
        controller: ai
        ports:
          ollama:
            port: 11434
          openwebui:
            port: &port 8080

    persistence:
      openwebui:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          ai:
            openwebui:
              - path: /data

      models:
        existingClaim: "{{ .Release.Name }}-models"
        advancedMounts:
          ai:
            ollama:
              - path: /root/.ollama

    route:
      app:
        hostnames:
          - ai.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
