---
web:
  port: ${GATUS_WEB_PORT}

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/52580954
  link: https://github.com/marcocondrache
  buttons:
    - name: Github
      link: https://github.com/marcocondrache
    - name: Homelab
      link: https://github.com/marcocondrache/hive

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux.marcocondrache.com
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
