---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tuliprox-deny-ipv6-egress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: tuliprox
  egressDeny:
    - toCIDRSet:
        - cidr: "::/0"
  egress:
    - toEntities:
        - all
