---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuliprox
spec:
  chartRef:
    kind: OCIRepository
    name: tuliprox
  interval: 1h
  values:
    controllers:
      tuliprox:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/euzu/tuliprox
              tag: 3.3.0@sha256:3940211e60f2800b57be286d06fb7ffca8726e9e7a0d4be835cea040f84b0f2b
            env:
              TZ: Europe/Rome
              TULIPROX_DOMAIN: tuliprox.marcocondrache.com
              TULIPROX_HOME: /app
              TULIPROX_HOST_IP: tuliprox.default.svc.cluster.local
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8901
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.marcocondrache.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
            subPath: config
          - path: /app/data
            subPath: data
          - path: /app/backup
            subPath: backup
          - path: /app/downloads
            subPath: downloads
          - path: /app/cache
            subPath: cache
      tmp:
        type: emptyDir
