---
clusterName: &clusterName hive

endpoint: https://192.168.0.51:6443

talosVersion: v1.9.5
kubernetesVersion: v1.32.3

additionalApiServerCertSans: &sans
  - 192.168.0.51
  - 127.0.0.1

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: 192.168.0.51 # queen leadership
    ipAddress: 192.168.0.51
    controlPlane: true
    installDisk: /dev/mmcblk0 # eMMC
    userVolumes:
      - name: DATA
        provisioning:
          diskSelector:
            match: disk.transport == "nvme"
          grow: true
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.transport == "nvme"
          maxSize: 100GiB
    networkInterfaces:
      - interface: end0
        dhcp: true

  # missing hardware
  # - hostname: royal-jelly.hive.internal # sustenance
  #   ipAddress: 192.168.0.52
  #   controlPlane: true
  #   installDisk: /dev/mmcblk0 # eMMC
  #   networkInterfaces:
  #     - interface: end0
  #       dhcp: true
  #       vip:
  #         ip: *vip

  # missing hardware
  # - hostname: royal-guard.hive.internal # protection
  #   ipAddress: 192.168.0.53
  #   controlPlane: true
  #   installDisk: /dev/mmcblk0 # eMMC
  #   networkInterfaces:
  #     - interface: end0
  #       dhcp: true
  #       vip:
  #         ip: *vip

  # missing hardware
  # - hostname: forager.hive.internal
  #   ipAddress: 192.168.0.59
  #   installDisk: /dev/mmcblk0 # eMMC
  #   networkInterfaces:
  #     - interface: end0
  #       dhcp: true

patches:
  - "@./patches/common/machine-files.yaml"
  - "@./patches/common/machine-kubelet.yaml"
  - "@./patches/common/machine-network.yaml"
  - "@./patches/common/machine-features.yaml"

controlPlane:
  nodeLabels: &nodeLabels
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  schematic: &schematic
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, more speed
        - init_on_alloc=0 # Less security, more speed
        - init_on_free=0 # Less security, more speed
        - mitigations=off # Less security, more speed
        - security=none # Less security, more speed
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

  patches:
    - "@./patches/controlplane/cluster.yaml"
    - "@./patches/controlplane/machine-features.yaml"

worker:
  nodeLabels: *nodeLabels
  schematic: *schematic
