---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: istio-istiod
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      hub: gcr.io/istio-release
      variant: distroless

    meshConfig:
      defaultConfig:
        proxyMetadata:
          ISTIO_DUAL_STACK: "true"

    pilot:
      env:
        ISTIO_DUAL_STACK: "true"

    gatewayClasses:
      istio:
        service:
          spec:
            ipFamilyPolicy: PreferDualStack
