---
originRequest:
  originServerName: external.marcocondrache.com

ingress:
  - hostname: marcocondrache.com
    service: &svc https://external-istio.istio-system.svc.cluster.local
  - hostname: "*.marcocondrache.com"
    service: *svc
  - service: http_status:404
