---
originRequest:
  originServerName: external.marcocondrache.com

ingress:
  - hostname: marcocondrache.com
    service: &service https://envoy-external.network.svc.cluster.local
  - hostname: "*.marcocondrache.com"
    service: *service
  - service: http_status:404
