---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - blackbox-exporter/ks.yaml
  - keda/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - grafana/ks.yaml
  - loki/ks.yaml
  - kromgo/ks.yaml
  - promtail/ks.yaml
  - smartctl-exporter/ks.yaml
  - silence-operator/ks.yaml
  - unpoller/ks.yaml
  - gatus/ks.yaml
