---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: papra
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      papra:
        annotations:
          reloader.stakater.com/auto: "true"

        strategy: RollingUpdate

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 3000

        containers:
          app:
            image:
              repository: ghcr.io/papra-hq/papra
              tag: 0.8.2-rootless
            env:
              PORT: &port 8000
              APP_BASE_URL: https://papra.marcocondrache.com
              DOCUMENTS_OCR_LANGUAGES: eng,ita,ron
              INGESTION_FOLDER_IS_ENABLED: true
              INGESTION_FOLDER_POST_PROCESSING_STRATEGY: delete
              INGESTION_FOLDER_PROCESSING_CONCURRENCY: 4
              AUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-secret"
                    key: PAPRA_SECRET

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 1Gi

    service:
      app:
        controller: papra
        primary: true
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          papra:
            app:
              - path: /app/app-data

      nas:
        type: nfs
        server: nas.hive.internal
        path: /mnt/tank/hive/papra
        advancedMounts:
          papra:
            app:
              - path: /app/ingestion

    route:
      app:
        hostnames:
          - papra.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: istio-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
