persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

defaultSettings:
  defaultDataPath: /var/longhorn
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 25
  allowCollectingLonghornUsageMetrics: false

defaultBackupStore:
  backupTarget: "s3://fsn1.your-objectstorage.com/cluster"
  backupTargetCredentialSecret: longhorn-s3
