---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  create-cluster:
    env:
      K3D_FIX_DNS: 0
      K3D_FIX_CGROUPV2: 1
    preconditions:
      - sh: "! k3d cluster list | grep -q 'lab-config'"
        msg: "lab-config cluster already exists"
    internal: true
    cmds:
      - k3d cluster create --config {{.ROOT_DIR}}/cluster.yaml
      - task: mount-bpf

  delete-cluster:
    internal: true
    preconditions:
      - sh: "k3d cluster list | grep -q 'lab-config'"
        msg: "lab-config cluster doesn't exist"
    cmds:
      - k3d cluster delete lab-config --config {{.ROOT_DIR}}/cluster.yaml

  # TODO: needed?
  mount-bpf:
    silent: true
    vars:
      NODES:
        sh: "k3d node list | grep -E 'lab-config-(server|agent)' | grep -v 'serverlb' | awk '{print $1}'"
    cmds:
      - for: { var: NODES }
        cmd: |
          docker exec -it {{.ITEM}} mount bpffs /sys/fs/bpf -t bpf
          docker exec -it {{.ITEM}} mount --make-shared /sys/fs/bpf

  write-config:
    internal: true
    cmds:
      - k3d kubeconfig get lab-config > {{.ROOT_DIR}}/kubeconfig

  init:
    cmds:
      - task: create-cluster
      - task: write-config
    silent: true

  reset:
    deps: [delete-cluster]
    cmds:
      - task: init
