---
clusterName: &clusterName hive

endpoint: https://k8s.hive.internal:6443

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.2

clusterPodNets:
  - "10.42.0.0/16"

clusterSvcNets:
  - "10.43.0.0/16"

additionalApiServerCertSans: &sans
  - k8s.hive.internal
  - &vip 10.0.30.20
  - 127.0.0.1

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  # missing: royal-jelly
  # missing: royal-guard
  - hostname: queen.hive.internal # queen leadership
    ipAddress: 10.0.30.21
    controlPlane: true
    installDiskSelector:
      type: nvme
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: 48:21:0b:55:c4:8a
        dhcp: true
        mtu: 9000
        vip:
          ip: *vip
        vlans:
          - &iot-vlan
            vlanId: 4
            mtu: 1500
            dhcp: false
            dhcpOptions:
              routeMetric: 4096

controlPlane:
  nodeLabels: &nodeLabels
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  kernelModules:
    - name: nbd
    - name: thunderbolt

  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc # Less security, faster puter
        - -init_on_free # Less security, faster puter
        - -selinux # Less security, faster puter
        - apparmor=0 # Less security, faster puter
        - init_on_alloc=0 # Less security, faster puter
        - init_on_free=0 # Less security, faster puter
        - iommu=pt # PCI Passthrough
        - amd_pstate=active # AMD P-State
        - mitigations=off # Less security, faster puter
        - security=none # Less security, faster puter
        - talos.auditd.disabled=1 # Less security, faster puter
      systemExtensions:
        officialExtensions:
          - siderolabs/amd-ucode
          - siderolabs/amdgpu
          - siderolabs/thunderbolt

  patches:
    # Configure containerd for spegel
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false

    # Disable search domain everywhere
    - |-
      machine: 
        network:
          disableSearchDomain: true

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Mount openebs-hostpath in kubelet
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/extra
              type: bind
              source: /var/mnt/extra
              options:
                - rbind
                - rshared
                - rw

    # Configure kubelet
    - |-
      machine:
        kubelet:
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 10.0.30.0/24

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 10.0.30.0/24

    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 10.0.30.20
              aliases:
                - k8s.hive.internal

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: 1048576   # Watchdog
          fs.inotify.max_user_instances: 8192    # Watchdog
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC
          net.ipv4.tcp_congestion_control: bbr   # BBR congestion control
          net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet
          net.ipv4.tcp_mtu_probing: 1            # Jumbo frames
          net.ipv4.tcp_rmem: 4096 87380 33554432
          net.ipv4.tcp_wmem: 4096 65536 33554432
          net.ipv4.tcp_window_scaling: 1
          sunrpc.tcp_slot_table_entries: 128     # NFS
          user.max_user_namespaces: 11255        # User Namespaces

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade
