machine:
  sysctls:
    fs.inotify.max_user_instances: 8192 # Watchdog
    fs.inotify.max_user_watches: 1048576 # Watchdog
    net.core.default_qdisc: fq
    net.core.rmem_max: 67108864 # Cloudflared / QUIC
    net.core.wmem_max: 67108864 # Cloudflared / QUIC
    net.ipv4.tcp_congestion_control: bbr
    net.ipv4.tcp_fastopen: 3
    net.ipv4.tcp_mtu_probing: 1 # Jumbo frames
    net.ipv4.tcp_window_scaling: 1
    net.ipv4.tcp_rmem: 4096 87380 33554432
    net.ipv4.tcp_wmem: 4096 65536 33554432
    sunrpc.tcp_slot_table_entries: 128 # NFS
    sunrpc.tcp_max_slot_table_entries: 128 # NFS
    user.max_user_namespaces: 11255 # User namespaces
