---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/home-operations/smartctl-exporter
      tag: 0.14.0
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
