apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: amd-gpu-deviceconfig
  namespace: kube-system
spec:
  driver:
    enable: false

  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
