---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tailscale
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    installCRDs: true

    ingressClass:
      enabled: false

    oauthSecretVolume:
      secret:
        secretName: tailscale-oauth

    operatorConfig:
      logging: debug
      hostname: "hive-operator"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      defaultTags:
        - "tag:hive-operator"

    proxyConfig:
      defaultTags: "tag:hive"

    apiServerProxyConfig:
      mode: "true"
