---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tailscale
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.86.5
  url: oci://ghcr.io/home-operations/charts-mirror/tailscale-operator
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tailscale
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    installCRDs: true

    ingressClass:
      enabled: false

    oauthSecretVolume:
      secret:
        secretName: tailscale-oauth

    operatorConfig:
      logging: debug
      hostname: "hive-operator"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      defaultTags:
        - "tag:hive-operator"

    proxyConfig:
      defaultTags: "tag:hive"

    apiServerProxyConfig:
      mode: "true"
