---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: network
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: 1.80.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: network
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: "tailscale"

    oauthSecretVolume:
      secret:
        secretName: tailscale-oauth

    operatorConfig:
      hostname: "hive-operator"
      defaultTags:
        - "tag:hive-operator"

    proxyConfig:
      defaultTags: "tag:hive"
