---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    rbac:
      bindings:
        tailscale:
          type: RoleBinding
          enabled: true
          forceRename: tailscale
          roleRef:
            kind: Role
            name: tailscale
          subjects:
            - identifier: tailscale

      roles:
        tailscale:
          type: Role
          enabled: true
          forceRename: tailscale
          rules:
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - get
                - update
                - patch

    serviceAccount:
      name: tailscale

    controllers:
      tailscale:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: latest
            env:
              TS_HOSTNAME: hive
              TS_USERSPACE: false
              TS_KUBE_SECRET: tailscale-oauth
              TS_ROUTES: 10.0.0.0/8
              TS_ENABLE_HEALTH_CHECK: true
              TS_TAILSCALED_EXTRA_ARGS: "--port=41641"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
