---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      immich:
        forceRename: immich
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.135.3
            env:
              TZ: Europe/Rome

              IMMICH_LOG_LEVEL: verbose
              IMMICH_MEDIA_LOCATION: /data/nas
              IMMICH_CONFIG_FILE: /config.json

              REDIS_HOSTNAME: immich-redis.default.svc.cluster.local

              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: uri

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 3072Mi

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.2
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        forceRename: immich
        controller: immich
        ports:
          http:
            port: 2283

      redis:
        controller: redis
        ports:
          redis:
            port: 6379

    persistence:
      config:
        type: configMap
        name: immich-config
        advancedMounts:
          immich:
            app:
              - path: /config.json
                subPath: config.json

      nas:
        type: nfs
        # TODO: Make this dynamic
        server: 192.168.0.131
        path: /mnt/tankpool/hive/immich
        advancedMounts:
          immich:
            app:
              - path: /data/nas

    route:
      app:
        hostnames:
          - immich.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 2283
