---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [3000]

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.2
            env:
              VENV_FOLDER: /venv
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.103.1@sha256:fc1d8a57dc5ca5fab67999416165d994ab78a7338b046c4b29f168033a6b7b38
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /config/.code-server
              - --extensions-dir
              - /config/.code-server
              - --port
              - "12321"
              - /config
            env:
              HASS_SERVER: http://localhost:8123
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
            primary: true
          code-server:
            port: 12321

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code-server:
              - path: /config

      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv

      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp
            code-server:
              - path: /tmp
                subPath: code-server-tmp
              - path: /nonexistent
                subPath: nonexistent

    route:
      app:
        hostnames:
          - hass.marcocondrache.com
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /code/
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /
            backendRefs:
              - identifier: app
                port: 12321
          - backendRefs:
              - identifier: app
                port: 8123
