---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hive-marcocondrache-com
spec:
  secretName: hive-marcocondrache-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: marcocondrache.com
  dnsNames: ["marcocondrache.com", "*.marcocondrache.com"]
