---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname internal.hive.marcocondrache.com
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname

      # TODO: try to disable hetzner loadbalancer
      load-balancer.hetzner.cloud/network-zone: "xxx"

      tailscale.com/expose: "true"
      tailscale.com/hostname: "hive-gateway"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.h.marcocondrache.com"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.h.marcocondrache.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: hive-marcocondrache-com-tls
