---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-internal-gateway-config
  namespace: kube-system
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
